apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: b00146c5-7602-494d-a765-dc40d8b6e19d
    subject: python-delete-pod_litmus
    workflow_id: a13473fc-1e8e-4ae8-96f2-9100f831e2a1
    workflows.argoproj.io/controller-instanceid: b00146c5-7602-494d-a765-dc40d8b6e19d
  name: python-delete-pod-1631014575
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-delete
        template: pod-delete
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - arguments: {}
    container:
      args:
      - kubectl apply -f /tmp/pod-delete.yaml -n {{workflow.parameters.adminModeNamespace}} |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Deletes a pod belonging to a deployment/statefulset/daemonset
            kind: ChaosExperiment
            metadata:
              name: pod-delete
              labels:
                name: pod-delete
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                      - apps
                      - apps.openshift.io
                      - argoproj.io
                      - batch
                      - litmuschaos.io
                    resources:
                      - deployments
                      - jobs
                      - pods
                      - pods/log
                      - replicationcontrollers
                      - deployments
                      - statefulsets
                      - daemonsets
                      - replicasets
                      - deploymentconfigs
                      - rollouts
                      - pods/exec
                      - events
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                      - deletecollection
                image: litmuschaos/go-runner:latest
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-delete
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "15"
                  - name: RAMP_TIME
                    value: ""
                  - name: FORCE
                    value: "true"
                  - name: CHAOS_INTERVAL
                    value: "5"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: TARGET_PODS
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: pod-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-pod-delete.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/chaosengine-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-delete
              labels:
                instance_id: 5a31d5f1-6968-49b9-9615-5aa631ac5dc1
                context: pod-delete_litmus
                workflow_name: python-delete-pod-1631014575
            spec:
              appinfo:
                appns: demo-develop
                applabel: app.kubernetes.io/instance=python-demo-develop
                appkind: deploymentconfig
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "20"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: FORCE
                          value: "false"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                    probe: []
              annotationCheck: "false"
              jobCleanUpPolicy: retain
    metadata:
      labels:
        weight: "10"
    name: pod-delete
    outputs: {}
  - arguments: {}
    container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (5a31d5f1-6968-49b9-9615-5aa631ac5dc1, )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
